blog_post_management_system/blog_post_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import home_page

urlpatterns = [
    path("",views.home_page,name = 'home_page'),
    path("customadmin/",include("customadmin.urls.urls")),
    path('admin/', admin.site.urls, name = "admin_view"),
    path("accounts/",include("accounts.urls")),
    path("blogs/",include("blogs.urls")),
    path("comments/",include("comments.urls")),
    path("likes/",include("likes.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_post_management_system/blogs/urls.py
from .views import BlogCreateView,BlogDetailView,BlogPostDeleteView,BlogPostListingView,BlogUpdateView
from django.urls import path,include


urlpatterns = [
    path('', BlogPostListingView.as_view(), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('<int:pk>/edit/', BlogUpdateView.as_view(), name='blog_edit'),
    path('<int:pk>/delete/', BlogPostDeleteView.as_view(), name='blog_delete'),
    # path('<int:pk>/comments/',include('comments.urls')),
    path('new/', BlogCreateView.as_view(), name='blog_create'),
]

blog_post_management_system/customadmin/urls.py
from django.urls import path,include
from  .views.views import MyLoginView,MyUserListView,UserListAjaxView,CreateUserView,UpdateUserView,MyUserDeleteView,UserProfileView,LogoutView
# from django.contrib.auth.templates 

app_name = "user"

urlpatterns = [
    path("", MyLoginView.as_view(), name="admin_login"),
    path("user/", MyUserListView.as_view(), name="user-list"),
    path("logout",LogoutView.as_view(),name="logout"),
    path("user-list-ajax/", UserListAjaxView.as_view(), name="user-list-ajax"),
    path("user/create", CreateUserView.as_view(), name="user-create"),
    path("user/<pk>/", UserProfileView.as_view(), name="profile"),
    path("user/<pk>/update/", UpdateUserView.as_view(), name="user-update"),
    path("user-delete/<pk>/delete", MyUserDeleteView.as_view(), name="user-delete"),
]

blog_post_management_system/customadmin/urls/urls.py
from django.urls import path,include
from  ..views.views import MyLoginView,MyUserListView,UserListAjaxView,CreateUserView,UpdateUserView,MyUserDeleteView,UserProfileView,LogoutView
# from django.contrib.auth.templates 

# app_name = "root"

urlpatterns = [
    path("",include('customadmin.urls.account_urls')),
    path("posts/",include('customadmin.urls.posts_urls')),

    # path("", MyLoginView.as_view(), name="admin_login"),
    # path("user/", MyUserListView.as_view(), name="user-list"),
    # path("logout",LogoutView.as_view(),name="logout"),
    # path("user-list-ajax/", UserListAjaxView.as_view(), name="user-list-ajax"),
    # path("user/create", CreateUserView.as_view(), name="user-create"),
    # path("user/<pk>/", UserProfileView.as_view(), name="profile"),
    # path("user/<pk>/update/", UpdateUserView.as_view(), name="user-update"),
    # path("user-delete/<pk>/", MyUserDeleteView.as_view(), name="user-delete"),
    
]

blog_post_management_system/customadmin/models.py
from django.db import models

# Create your models here.

blog_post_management_system/customadmin/forms/blogs_form.py
from django import forms
from blogs.models import BlogPost
from django.core.exceptions import ValidationError


class BlogPostForm(forms.ModelForm):
    """This form is used to make a blog for particular user"""

    class Meta:
        model = BlogPost
        fields = ["title", "content"]

    title = forms.CharField(
        max_length=200,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        error_messages={
            "required": "Title is required",
            "max_length": "Title is too long",
        },
    )

    content = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control"}),
        required=True,
        error_messages={"required": "Content is required"},
    )

    def clean_content(self):
        content = self.cleaned_data.get("content")
        if len(content) < 20:
            raise ValidationError("Content should be at least 20 characters long.")
        return content

blog_post_management_system/customadmin/views/PostsView.py
from blogs.models import BlogPost
from django.views.generic import (
    ListView,
    DeleteView,
    DetailView,
    CreateView,
    UpdateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from customadmin.forms.blogs_form import BlogPostForm
from django.urls import reverse_lazy
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect,JsonResponse
from django.views import View
from customadmin.mixins import HasPermissionsMixin
from django.template.loader import get_template
from django.db.models import Q
from customadmin.views.generics import MyCreateView, MyListView
from customadmin.forms.blogs_form import BlogPostForm
from django.contrib import messages
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from likes.models import Like
from comments.models import UserComments
from django.contrib.auth.models import User

class listBlogs(MyListView):
    """This view is used to list all the blogs"""

    model = BlogPost
    template_name = "Blogs/blog_list_admin.html"
    context_object_name = "posts"
    ordering = ["-date_published"]

    def get_queryset(self):
        """Override queryset to add extra functionality"""
        return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["opts"] = self.model._meta
        context_data["count"] = self.model.objects.count()
        return context_data


################ AJAX view for post listing table #################

class BlogListAjaxView(View, HasPermissionsMixin):
    """
    Ajax-Pagination view for Bloglisting
    """
    template_name = "Blogs/blog_list_admin.html"
    model = BlogPost

    def get_queryset(self):
        queryset = self.model.objects.all()
        return queryset

    def _get_is_superuser(self, obj):
        """Get boolean column markup."""
        t = get_template("core/partials/list_boolean.html")
        return t.render({"bool_val": obj.is_superuser})

    def is_orderable(self):
        """Check if order is defined in dictionary."""
        return True

    def _get_actions(self, obj):
        """Get actions column markup."""
        t = get_template("partials/list_actions.html")
        opts = self.model._meta
        return t.render(
            {
                "obj": obj,
                "opts": opts,
                "has_change_permission": self.has_change_permission(self.request),
                "has_delete_permission": self.has_delete_permission(self.request),
            }
        )

    def _get_check(self, active: bool):
        template = get_template("partials/list_boolean.html")
        return template.render({"bool_val": active})

    def prepare_results(self, qs):
        """Prepare final result data here."""

        data = []
        
        for post in qs:
            print(post)
            current_user = User.objects.get(id=post.author_id)
            data.append(
                {
                   "id": post.id,
                   "title":post.title,
                   "content":post.content,
                   "date_published":post.date_published,
                   "author_id":current_user.username,
                   "action":self._get_actions(post)
                }
            )
        return data

    def get(self, request, *args, **kwargs):
        context_data = {}
        start = int(request.GET.get("start", 0))
        length = int(request.GET.get("length", 10))
        draw = int(request.GET.get("draw", 1))
        search_value = request.GET.get("search[value]", "").strip()
        queryset = self.model.objects.all()

        # if search_value:
        #     queryset = queryset.filter(
        #         Q(title__icontains=search_value) |
        #         Q(content__icontains=search_value) |
        #         Q(date_published__icontains=search_value) |
        #         Q(author_id__icontains=search_value)
        #     )

        total_records = self.model.objects.count()
        filtered_records = queryset.count()
        queryset = queryset[start:start + length]
        data = self.prepare_results(queryset)
        
        context_data["data"] = data
        context_data["draw"] = draw
        context_data["recordsTotal"] = total_records
        context_data["recordsFiltered"] = filtered_records

        return JsonResponse(context_data)
    

class UpdatePostView(UpdateView,View):
    model = BlogPost
    form_class = BlogPostForm
    template_name = 'Blogs/blog_update_admin.html'
    success_url = reverse_lazy('admin_post:list-post-admin') 


class CreateBlogView(CreateView):
    model = BlogPost
    form_class = BlogPostForm
    template_name = "Blogs/blog_create_admin.html"
    success_url = reverse_lazy('admin_post:list-post-admin') 

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class DeleteBlogView(DeleteView):
    """This view is used to delete existing blog"""

    def get(self, request, pk):
        try:
            current_blog = BlogPost.objects.get(id=pk)
            current_blog.delete()
            messages.success(self.request, f"Blog deleted.")
            return HttpResponseRedirect(reverse("admin_post:list-post-admin"))
        except current_blog.DoesNotExist:
            return HttpResponse("Given post does not exist!")


class BlogDetailView(DetailView):
    """This view is used to show selected blog"""

    template_name = "Blogs/blog_detail_admin.html"
    model = BlogPost
    fields = ['id','title','content', 'author', 'date_published','likes_count']

    def get_object(self):
        blog_post = super().get_object()
        return blog_post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        blog_post = self.get_object()
        likes = Like.objects.filter(post_id=blog_post).count()

        context['likes'] = likes
        context['blog_id'] = blog_post.id
        comments = UserComments.objects.filter(post_id=blog_post)
        context['comments'] = comments
        return context

    def get(self, request, pk, *args, **kwargs):
        return super().get(request, pk, *args, **kwargs)


class DeleteCommentView(DeleteView):
    """This view is used to delete existing comments"""
    model = UserComments

    def get_success_url(self):
        """Redirect to the blog post detail page after successful deletion"""
        return reverse("admin_post:blogpost-detail", kwargs={"pk": self.object.post_id_id})
    
    def get(self, request, pk):
        try:
            current_comment = self.model.objects.get(id=pk)
            current_comment.delete()
            messages.success(self.request, f"Comment deleted.")
            return HttpResponseRedirect(reverse("admin_post:blogpost-detail"), kwargs={"pk": current_comment.post_id})
        except current_comment.DoesNotExist:
            return HttpResponse("Given comment does not exist!")
        
class CreateCommentView(CreateView):
    
    model = BlogPost

    def form_valid(self, form):
        form.instance.post_id = BlogPost.objects.get(pk=self.kwargs["blog_id"])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("list_comment", kwargs={"pk": self.kwargs["pk"]})
    
    def get(self, request, pk):
        try:
            current_comment = UserComments.objects.get(id=pk)
            current_comment.delete()
            messages.success(self.request, f"Comment deleted.")
            return HttpResponseRedirect(reverse("admin_post:blogpost-detail"), kwargs={"pk": current_comment.post_id})
        except current_comment.DoesNotExist:
            return HttpResponse("Given comment does not exist!")

        




    

blog_post_management_system/customadmin/views/generics.py
from typing import Any

from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import ValidationError
from django.http import HttpRequest, HttpResponse
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

# from just_move_python.domain.user.models import User, UserRoleNames

from ..mixins import HasPermissionsMixin, ModelOptsMixin
from ..templatetags.misc_filters import admin_urlname

MSG_CREATED = '"{}" created successfully.'
MSG_UPDATED = '"{}" updated successfully.'
MSG_DELETED = '"{}" deleted successfully.'
MSG_CANCELED = '"{}" canceled successfully.'

find_element = lambda arr, target: target in arr


class MyPermissionRequiredMixin(PermissionRequiredMixin):
    raise_exception = True

    def get_permission_required(self):
        """Default to view and change perms."""
        opts = self.model._meta
        codename_view = get_permission_codename("view", opts)
        codename_change = get_permission_codename("change", opts)
        view_perm = f"{opts.app_label}.{codename_view}"
        change_perm = f"{opts.app_label}.{codename_change}"
        perms = (view_perm, change_perm)
        return perms


class SuccessMessageMixin(object):
    """CBV mixin which adds a success message on form save."""

    success_message = ""

    def get_success_message(self, message: str):
        return self.success_message

    def form_valid(self, form):
        response = super().form_valid(form)
        success_message = self.get_success_message()
        if success_message:
            messages.success(self.request, success_message)
        return response


class MyLoginRequiredMixins(LoginRequiredMixin):
    """
    Custom Login Required Mixins that override the handle_no_permission method
    """

    def handle_no_permission(self) -> HttpResponseRedirect:
        """Redirect to the admin login page"""
        if self.request.user.is_authenticated:
            return render(
                self.request,
                "403.html",
                status=403,
            )
            # return HttpResponse("You don't have admin permission")
        return redirect("user:admin_login")


class MyListView(
    MyLoginRequiredMixins,
    MyPermissionRequiredMixin,
    ModelOptsMixin,
    HasPermissionsMixin,
    ListView,
):
    """ListView CBV with LoginRequiredMixin and PermissionRequiredMixin."""

    def has_permission(self):
        if self.request.user.is_staff == True:
            return True
        else:
            return super().has_permission()


class MyCreateView(
    MyLoginRequiredMixins,
    MyPermissionRequiredMixin,
    ModelOptsMixin,
    SuccessMessageMixin,
    HasPermissionsMixin,
    CreateView,
):
    """CreateView CBV with LoginRequiredMixin, PermissionRequiredMixin
    and SuccessMessageMixin."""

    def get_success_message(self):
        return MSG_CREATED.format(self.object)

    def get_success_url(self):
        opts = self.model._meta
        return reverse(admin_urlname(opts, "list"))

    def has_permission(self):
        if self.request.user.is_staff == True:
            return True
        else:
            return super().has_permission()

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if not self.request.user.is_superuser:
            messages.error(
                self.request,
                "You don't have permission to create company",
            )
            return HttpResponseRedirect(reverse("user:user-list"))
        return super().get(request, *args, **kwargs)


class MyDeleteView(
    MyLoginRequiredMixins,
    MyPermissionRequiredMixin,
    ModelOptsMixin,
    SuccessMessageMixin,
    HasPermissionsMixin,
    DeleteView,
):
    def get_success_message(self):
        return MSG_DELETED.format(self.object)

    def has_permission(self):
        if self.request.user.is_staff == True:
            return True
        else:
            return super().has_permission()


class MyUpdateView(
    LoginRequiredMixin,
    MyPermissionRequiredMixin,
    SuccessMessageMixin,
    ModelOptsMixin,
    HasPermissionsMixin,
    UpdateView,
):
    """UpdateView CBV with LoginRequiredMixin, PermissionRequiredMixin
    and SuccessMessageMixin."""

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        try:
            return super().get(request, *args, **kwargs)
        except ValidationError:
            messages.error(request=request, message="Invalid URL")
            return redirect("user:user-list")

    def get_permission_required(self):
        """Default to view and change perms."""
        opts = self.model._meta
        codename_view = get_permission_codename("view", opts)
        codename_change = get_permission_codename("change", opts)
        view_perm = f"{opts.app_label}.{codename_view}"
        change_perm = f"{opts.app_label}.{codename_change}"
        perms = (view_perm, change_perm)
        return perms

    def get_success_message(self):
        return MSG_UPDATED.format(self.object)

    def get_success_url(self):
        opts = self.model._meta
        return reverse(admin_urlname(opts, "list"))

    def has_permission(self):
        if self.request.user.is_staff == True:
            return True
        else:
            return super().has_permission()

blog_post_management_system/customadmin/templates/includes/image_cropper.html
{% load static %}

<div class="rw_form_inputs" id="trigger-image">
  <label class="rw_form_label">{{image.label}}&nbsp; (only jpeg, png, jpg allowed) *</label>

  <div class="rw_input img-preview-div">
    <input
      class="file-input"
      type="file"
      hidden
      name="image"
      accept=".png, .jpg, .jpeg"
      id="file-input"
      {% if multiple %} multiple {% endif %}
    />
    <img
      id="image-div-input-preview"
      src={% if image.value %} {{image.value.url}} {% elif image.image %} {{image.image.url}} {% else %}"{% static '/images/uplaod-image.jpg' %}" {% endif %}
      alt=""
    />
  </div>
  <span id="image-error" class="text-danger"> {{image.errors}} </span>
</div>

<div class="image-cropper-popup">
  <div class="custom-model-inner input-modal-inner">
    <div class="close-btn">×</div>
    <div class="custom-model-wrap pt-4">
      <div class="pop-up-content-wrap">
        <main class="page">
          <!-- input file -->
          <div class="box"></div>
          <!-- leftbox -->
          <div class="box-2 m-auto">
            <div class="result"></div>
          </div>
          <!--rightbox-->
          <div class="box-2 img-result hide mt-3">
            {% if preview is not None %}
            <img
              class="cropped"
              style="height: 50%; width: 50%"
              id="image-div-input-preview"
              src=""
              alt=""
            />
            <!-- result of crop -->
            {% endif %}
          </div>
          <!-- input file -->
          <div class="box mt-3">
            <div class="options hide"></div>
            <div class="bottom-btn-row">
              <!-- save btn -->
              {% if preview is not None %}
              <button class="rw_btn preview">Preview</button>
              {% endif %}
              <button type="button" class="rw_btn save">Save</button>
            </div>
          </div>
        </main>
      </div>
    </div>
  </div>
</div>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"
  integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>
<script>
  document.getElementById("file-input").addEventListener("change", (e) => {
    $(".image-cropper-popup").addClass("model-open");
  });
  $(".close-btn").click(function () {
    $(".image-cropper-popup").removeClass("model-open");
  });
</script>

blog_post_management_system/customadmin/templates/includes/messages.html
{% if messages %}
{% for message in messages %}
<div
  class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show"
  role="alert">
  {{message}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<script>
    setTimeout(() => {
      $("button[data-bs-dismiss=alert]").click()
    }, 2000);  
</script>
{% endfor %}
{% endif %}

blog_post_management_system/customadmin/templates/includes/sidebar_header.html
{% load static %}
{% load misc_filters %}
<header class="rw_header_wrapper">
    <div class="rw_header_inner">
        {% breadcrumb_trail request %}
        <div class="header_profile dropdown">
            <div class="header_title">
                <h3>Hello, {{request.user.username}}</h3>
            </div>

            <a href="{% url 'user:logout' %}" class="btn btn-outline-danger text-dark logout-btn">Logout</a> 
        </div>
    </div>
    <div class="rw_sidebar">
        <div class="header_logo">
            {% if request.user.is_admin %}
            <a href="{% url 'user-list' %}">
                <img src="{% static 'images/logo.svg' %}" alt="logo">
            </a>
            {% else %}
            <img src="{% static 'images/logo.svg' %}" alt="logo">
            {% endif %}
        </div>
        <ul>
            {% comment %} USERS  {% endcomment %}
            {% if request.user.is_superuser %}
            
            <li><a href="{% url 'user:user-list' %}" {% if '/user' in request.path %} class="active" 
                {% endif %} title="Users"><img src="{% static 'images/icons/group.svg' %}" alt="user">
                <span>Users</span>
            </a></li>
            {% endif %}

                {% comment %} POSTS  {% endcomment %}
            <li><a href="{% url 'admin_post:list-post-admin' %}" {% if '/post' in request.path %} class="active" 
                {% endif %} title="posts"><img src="{% static 'images/icons/dashboard.svg' %}" alt="post">
                <span>Posts</span>
            </a></li>
            

            {% comment %} ACTIVE BREAKS {% endcomment %}
            {% comment %} {% if request.user.is_admin %} {% endcomment %}
            {% comment %} <li><a href="{% url 'activebreak:activebreak-list' %}" {% if '/break' in request.path %} class="active" 
                {% endif %} title="Active Breaks"><img src="{% static 'images/icons/time_white.svg' %}" alt="activebreak">
                <span>Active Breaks </span>
            </a></li>
            {% endif %} {% endcomment %}
        </ul>
    </div>
</header>